//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mitredeneme.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_sonuc
    {
        public int id { get; set; }
        public string kullaniciAdi { get; set; }
        public string test1 { get; set; }
        public string test2 { get; set; }
        public string time { get; set; }
    }
}
